### PR TITLE
[Feature/Aggregate] Compact table display by Evence

### PR DESCRIPTION
**Pull request by jimmy-lan**
This pull request adds the compact table display created by Evence.

### CODE REVIEW

**Comment by jimmy-lan** [comment]
Hi @evencewang, by contributing to the Habits CLI,

* You agree that your code will be licensed under GPL, as defined in the root of this repository (i.e., the `LICENSE` file); AND
* You agree that your code will become open-sourced and included in this repository; AND
* You authorize the use of your code in the `Habits CLI` repository; AND
* Since your code is blended or may become blended with my code, you are aware and agree to not restrict my use of this code. The reason for this condition is that some code from my personal projects may be copied to other places for other uses (the code might also be licensed differently), and it will be very difficult to keep track of your code when performing this process. _If you end up making a significant amount of contributions to this project, we can discuss and change this term._

Please make sure that you have read, understood, and agreed to the above. If you do not agree, these changes will, unfortunately, be returned to you. If this is the case, I still encourage you to add your changes to your forked repository.

If you agree, please clearly indicate that you agree to the above terms and conditions. If this is the case, you also agree that the above terms and conditions are binding agreements between us. Thanks so much for your contributions!

Best,

Jimmy

**Comment by lanyanxiang** [comment]
@evencewang As an amendment to the above, this pull request includes your previous contributions and some refactoring work done by me: https://github.com/lanyanxiang/habits-cli/pull/83.

**Comment by jimmy-lan** [comment]
@evencewang As an amendment, some refactoring work has been done on this pull request. See the changes here: https://github.com/lanyanxiang/habits-cli/pull/83.

**Comment by evencewang** [comment]
@lanyanxiang I agree to above terms and conditions.

**Comment by jimmy-lan** [comment]
@evencewang Thanks! 🚀

**Pull request merged**
